### ISSUE TITLE
Partial formating yields wrong intendation deep

### ISSUE THREAD

**Issue by laeubi** [eclipse/lemminx#1485]
If I format only a part of the document one gets wrong indentation, e.g.:

## Current
![image](https://user-images.githubusercontent.com/1331477/219618459-42eaf694-f35a-46cb-957e-f6b11fe2bb66.png)

## Expected
![image](https://user-images.githubusercontent.com/1331477/219618533-547d541f-8ec8-477d-9547-96450b68abb9.png)

**Comment by fbricon** [comment]
Can you check in VS Code?

**Comment by angelozerr** [comment]
@laeubi could you share your xml file please in order we can test with the same usecase than you.

**Comment by laeubi** [comment]
1. [pom.xml.zip](https://github.com/eclipse/lemminx/files/10766260/pom.xml.zip)
2. mark L 118 - 131
3. press STRG+SHIFT+F
4. You will see state from first screenshot
5. press SHIFT+TAB two times to get expected result.

**Comment by fbricon** [comment]
There's a bug somewhere in Lemminx, but not the one you see (which is most likely WWD specific):
![Feb-17-2023 13-40-20](https://user-images.githubusercontent.com/148698/219656432-cd5b9890-3dd8-4028-9811-3c9a953ae5b2.gif)

Section formatting leaks to the rest of the document for some reason (`<type>eclipse-plugin</type>` is messed up L138)

**Comment by fbricon** [comment]
the issue seen in Eclipse might be LSP4E sending the wrong indentation character to lemminx

**Comment by laeubi** [comment]
I trust you as the experts in this area to direct this to the right place, as a user I have no idea what all makes the difference here and can only guess it is related to Lemminx as the editr claims to be Lemminx based :-)

**Comment by angelozerr** [comment]
@JessicaJHee could you see please the problem of @fbricon described in https://github.com/eclipse/lemminx/issues/1485#issuecomment-1434591999 thanks

**Comment by angelozerr** [comment]
@laeubi if you format the whole file in WWD and after you retry your usecase. Is it working better?

**Comment by laeubi** [comment]
@angelozerr I'm not sure about WWD? I'm just using Eclipse with m2e, so if you download for example the last ibuild, create a new project and copy the file into it one should be able to reproduce (and probably see what/if other components are interfering here).

**Comment by angelozerr** [comment]
Sorry @laeubi, I'm tootechnical:  WWD is the eclipse plugin which consumes lemminx: if you format the whole file in Eclipse IDE and after you retry your usecase. Is it working better?

**Comment by angelozerr** [comment]
> There's a bug somewhere in Lemminx, but not the one you see (which is most likely WWD specific):

@fbricon this problem has been fixed by @JessicaJHee with https://github.com/eclipse/lemminx/pull/1486

**Comment by angelozerr** [comment]
@laeubi the problem comes from WWD [WWD](https://github.com/eclipse/wildwebdeveloper) which doesn't allow to configure spaces / tabs, see https://github.com/eclipse/wildwebdeveloper/issues/872

Indeed, if you show spaces / tabs
![image](https://user-images.githubusercontent.com/1932211/220042718-38c2d627-ee9c-4709-9c32-dba0cbd0ed82.png)

you will notice that the indentation that you expect is spaces (and not tabs)

![image](https://user-images.githubusercontent.com/1932211/220042915-759df298-30fa-451f-8919-8a7327b115c0.png)

As WWD cannot configure the spaces / tabs for a given language like XML, it uses the default spaces / tabs

![image](https://user-images.githubusercontent.com/1932211/220043142-17b84f9b-2883-437b-9b1d-983c2788c849.png)


which uses tabs and not spaces. So when you format your select, the format uses tabs and not spaces. if you change to spaces

![image](https://user-images.githubusercontent.com/1932211/220043312-d8b7f826-2165-4185-9d4a-d519385d958c.png)


It should work, but all editor will uses this configuration (ex : Java, etc).

It is not a trivial issue because it requires some changes to Eclipse Platform. I created a draft PR https://github.com/eclipse-platform/eclipse.platform.text/pull/130

I close this issue since it is an issue of Eclipse Platform / WWD, please follow https://github.com/eclipse/wildwebdeveloper/issues/872

@mickaelistria I think https://github.com/eclipse-platform/eclipse.platform.text/pull/130
 become important, we have more and more issues about spaces / tabs configuration capability.

**Comment by laeubi** [comment]
@angelozerr thanks for the detailed analysis. I think for partial formatting, it would be great if lemminx would just use the existing style of the document, that most likely what a use will expect and desire.

**Comment by angelozerr** [comment]
I had this idea, we could do that for formatting, but the main problem is if you are in tabs configuration (like you are), if you press tabs, it will generate a tab although your XML sample uses spaces.
