### ISSUE TITLE
How to contribute to `completionItem/resolve` ?

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lemminx#616]
For Maven extension, we'd like to offer completion item documentation asynchronously (as it requires to read the pom which we cannot do for all proposals or completion would take to long).
Does the extension provide a way to "resolve" a completion item? I couldn't find an appropriate method.

**Comment by angelozerr** [comment]
No there is no possibility to do that, because today we need not that (performance are correct for any extension like XSD, DTD completion, etc).

Any contribution are welcome.  To do that, I suggest that you implement completion/resolve like 
https://github.com/eclipse/lemminx/blob/e314411f56594a29b86d0284f43ea66133e775a7/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/XMLTextDocumentService.java#L175

The XMLLanguageService should have a new method like `doResolveCompletionItem` which call the same method in https://github.com/eclipse/lemminx/blob/master/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/services/XMLCompletions.java

The `doResolveCompletionItem` must loop for ICompletionParticipant like https://github.com/eclipse/lemminx/blob/e314411f56594a29b86d0284f43ea66133e775a7/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/services/XMLCompletions.java#L491 and call the new method ICompletionParticipant #resolveCompletionItem (by default it should return null)

It's the main idea, if you need some more help, please ask me.

**Comment by mickaelistria** [comment]
This has become more important in lemminx-maven since adoption of Maven Central Search engine that doesn't provide description in its response; so we need to download the pom to show description and this shoudl be part of a `completionItem/resolve`.
cc @vrubezhny

**Comment by angelozerr** [comment]
Any contribution are welcome!
