### ISSUE TITLE
Problem markers are not always cleaned up when editor is closed in background

### ISSUE THREAD

**Issue by nitind** [eclipse/lemminx#715]
If I have a Generic Editor editor open with an XML file behind another editor, the problem markers associated with the background generic editor are not cleaned up if I close it using the Close Others style options from the foreground editor's part tab.

**Comment by angelozerr** [comment]
I close this issue since it's not a problem coming from XML Language Server LemMinx but more a problem with LSP4E. 

Indeed on the LSP didClose the XML Language Server, publish empty diagnostics for the closed file. In LSP4E the didClose is called when the editor is closed. It seems that in multi page editor context, the didClose is not called. Please create an issue in Eclipse LSP4E. 

Thanks.
