### ISSUE TITLE
Linting makes editing hard

### ISSUE THREAD

**Issue by deathaxe** [eclipse/lemminx#963]
![grafik](https://user-images.githubusercontent.com/16542113/104845944-47759300-58d8-11eb-8434-af438cdce171.png)

The screenshot shows a simple file which only misses the end tag `</xs:schema>`. This little issue results in the whole document being marked invalid, which doesn't help much. The file becomes harder to read while editing and doesn't tell much about the origin of the error.

I'd expect only the opening tag name and/or the end of the document being marked invalid. The content in between is very correct.

**Comment by angelozerr** [comment]
This behavior comes from https://github.com/eclipse/lemminx/pull/897#issuecomment-703644336

The main idea is to highlight the error from the start tag which is broken to the offset reported by Xerces:

> I'd expect only the opening tag name and/or the end of the document being marked invalid

Ideally it should be nice to highlight the start/end tag but diagnostic support just one range.

**Comment by deathaxe** [comment]
When I was working on the xsd file huge blocks of the document were highlighted this way while adding or rearranging tags. Even when just writing down a new document from top to down one ends up in huge blocks being marked this way.

I don't find it useful and very distracting.

Maybe the client can detect large regions and disable inline markup.

**Comment by angelozerr** [comment]
> When I was working on the xsd file huge blocks of the document were highlighted this way while adding or rearranging tags. 

You should have code action which should help you to fix broken xml.

> I don't find it useful and very distracting.

Ok thanks for your feedback, I will see how we could improve your usecase.

**Comment by deathaxe** [comment]
Yes, code actions are available. Haven't used them much though as it always involves using the mouse to hover the annotation and selecting the desired ones. It seems to work in general though.

Most things can quickly be fixed via auto-completions which proposes correct closing tags. Not a problem. It's just the fact huge blocks of the document being marked most the time while working on a document. It's so to say a normal use case to have broken XML during authoring.

**Comment by predragnikolic** [comment]
Hello, 

> Ideally it should be nice to highlight the start/end tag but diagnostic support just one range.

Maybe `diagnostic.relatedInformation: DiagnosticRelatedInformation[]` may help for this use case? Here is an [example](https://code.visualstudio.com/updates/v1_22#_related-information-in-errors-and-warnings).

> Haven't used them much though as it _always involves using the mouse_ to hover the annotation and selecting the desired ones. It seems to work in general though.

@deathaxe, you can assign a keyboard shortcut to trigger code actions. 
Because I know you use Sublime text, here is it :)
```
{ "keys": ["ctrl+."], "command": "lsp_code_actions" },
```

**Comment by angelozerr** [comment]
> Maybe diagnostic.relatedInformation: DiagnosticRelatedInformation[] may help for this use case?

At first relatedInformation is not supported by all LSP client (ex: Eclipse IDE doesn't support it). We use relatedInformation when you have a XML bind with a XSD file which is not well formatted.

**Comment by angelozerr** [comment]
We cover the range from start tag to offset reported by xerces to support correctly code action.

For instance with this XML:

```xml
<schema attr
```

xerces report the offset after `attr`. We can provide code actions after this `attr` content with `/>` or `></schema>`. 

In old version the range was just the start tag name (schema) and code actions inserted  `/>` or `></schema>` before the `attr`.

The main problem is that code action uses the error range to retrieve the offset where `/>` or `></schema>` must be inserted. I know LSP 3.16 specify that code action can have a data. 

When a diagnostic will be generated we could create a range with start tag name and set in the data the offset where xerces has reported the error.

**Comment by predragnikolic** [comment]
@mickaelistria thanks for all these information. 

> This is actually the proper way, as it's language-specific semantic ("we're in a comment block, so we should start by a *" is not something a text editor can or should know about)

After reading all what you said, I would say that it is the proper LSP way to do it,
but I would keep in mind the LSP way doesn't always guarantee the best user experience.

> Implementing it in the client can of mean that the client has to start parsing the document to know whether the edit is in a comment area. That's a bad smell: with LSP, everything that requires parsing should take place in the LS, not in the client.
> ref: https://github.com/eclipse/wildwebdeveloper/issues/599#issuecomment-762035681

Here is the reason why I thought that the text editor should implement this.
In cases where I expect immediate feedback, (example. I want the `*` as soon as I press `enter`)
if the client has its own parser that detects comment, it will do it probably noticeably faster that doing it over with LSP. 

I tried the PR that you linked - https://github.com/redhat-developer/yaml-language-server/pull/389
And while I can see a slight delay when pressing `enter` and showing the *, the user experience is still good, I would say great, but on the other hand it would be good if the delay didn't exist at all.

In both applications(VS Code, Sublime Text), I just held down `enter`. Here is the difference:
![output](https://user-images.githubusercontent.com/22029477/104955284-458bfc80-59ca-11eb-8394-706a270c5456.gif)

Comparing both of those approaches(text editor implementation vs language server implementation) can have it's pros and cons. But because this is LSP spec, doing it on the server now make more sense to me.

**Comment by angelozerr** [comment]
>Ideally it should be nice to highlight the start/end tag but diagnostic support just one range.

> Maybe diagnostic.relatedInformation: DiagnosticRelatedInformation[]

@predragnikolic thanks a lot for your suggestion, I will try to investigate your idea.

@deathaxe is Sublime LSP client can support relatedInformation?

**Comment by deathaxe** [comment]
If not yet, it may learn it. That's what I read from @predragnikolic's suggestions. I am not yet very familiar with that approach, but the main question might be whether the result is something common which all language servers make use of, or whether the solution will be something specific. Not sure how to handle the latter case.

**Comment by predragnikolic** [comment]
Here is how other language servers handle that case.
The TypeScript server generates 2 diagnostics:
- one at the open tag location
- and the other at the end where the missing tag is expected.

![examplee](https://user-images.githubusercontent.com/22029477/105090899-53f81800-5a9f-11eb-98fc-bd8096347910.png)

> The main problem is that code action uses the error range to retrieve the offset where /> or ></schema> must be inserted. I know LSP 3.16 specify that code action can have a data.

I am not sure If having 2 diagnostics, like in the image above, would provide enough information for the server to calculate where to put the closing tag.

**Comment by predragnikolic** [comment]
> Does the Sublime LSP client  support relatedInformation?

Yes, LSP for Sublime Text does support it. 
<details>
<summary>Here is an example gif</summary>

Keep in mind that I hard coded the response to include the `diagnostic.relatedInformation` field, so this is actually not provided by the language server, but rather just for demonstrating purposes.

Sublime Text just shows related diagnostics information in the hover popup, when hovering over the diagnostics.

![output](https://user-images.githubusercontent.com/22029477/105093161-93743380-5aa2-11eb-80ae-adb3e0ddd78b.gif)
```
    diagnostic['relatedInformation'] = [{
            'location': {
                'uri': '/home/predrag/Documents/modulll/src/App.jsx',
                'range': {
                    'start': { 'line': 9, 'character': 15 },
                    'end' : { 'line': 9, 'character': 15 }
                },
            },
            'message': 'Missing closing tag here'
    }]
```

VS Code show `relatedInformation` in the diagnostics panel and the hover popup.
![image](https://user-images.githubusercontent.com/22029477/105093561-37f67580-5aa3-11eb-9786-4b82033a2664.png)

</details>

**Comment by datho7561** [comment]
Something that may prevent this from being implemented is that we depend on the end of the error range in order to generate the `CodeAction` to close the element. This is no issue for clients that support `relatedInformation`, since the correct end tag location is in the `relatedInformation`. We can't take this approach in clients that don't support `relatedInformation`.

These are some options that I can see to move forward with this:
1. Restructure LemMinX's CodeActions so they only depend on the start of the error range. This might take a while. It also means we have to calculate the close tag location twice: once for the diagnostic and once for the CodeAction.
2. Don't support CodeActions at all on clients that don't support related info
3. Keep the old diagnostic range on clients that don't support. This sounds like it would cause more headaches than its worth.

Please let me know if you can think of other ways to go about this.

**Comment by angelozerr** [comment]
> We can't take this approach in clients that don't support relatedInformation.

I think we should follow this idea. The diagnostics will work for any LSP client but for LSP client which support relatedInformation, the higlighting error will be better.

It looks like Outline with symbols. If LSP client can support symbol hierarchy, the Outline renderer will be better.

**Comment by datho7561** [comment]
@angelozerr so do you mean option 3?

**Comment by angelozerr** [comment]
If old in "Keep the old diagnostic range on clients that don't support." means current behavior, I would say "yes"
