### ISSUE TITLE
onXMLContent items not showing up after updating to latest snapshot

### ISSUE THREAD

**Issue by kathrynkodama** [eclipse/lemminx#997]
I recently updated the Liberty LemMinx extension per: https://github.com/eclipse/lemminx/pull/992

Now it seems that none of the completion items in the `onXMLContent` method are showing up. It doesn't seem to even be entering that method. I updated to the latest LemMinx snapshot (`0.15.1-SNAPSHOT`) and updated the `onXMLContent` method: https://github.com/OpenLiberty/liberty-language-server/pull/43/files#diff-97c4e86ff0569263f65866e874c736fecbfb36cbf00008e3cb68e8a9cca782c2R31.

Is there something else that needs to be configured? Any insight would be appreciated

**Comment by datho7561** [comment]
Tried it, still seems to work for me:

![Screenshot from 2021-03-01 10-13-36](https://user-images.githubusercontent.com/22376627/109517340-24add100-7a77-11eb-98d0-9c7d60e6dc27.png)

If you are running the vscode-xml from the VS Code Marketplace, that could be the problem, since it comes with LemMinX 0.15.0, where the changes haven't been added yet. If this is the case, it should work if you [build vscode-xml from source](https://github.com/redhat-developer/vscode-xml/blob/master/CONTRIBUTING.md#steps). If you are doing this already please ignore.

It could also be that the issue doesn't show up on Linux. I'll try on Windows as well.

**Comment by kathrynkodama** [comment]
@datho7561 thank you! That was the problem, building vscode-xml from the source fixed it.
